### ISSUE TITLE
Platform floating out of sync with other platforms 

### ISSUE THREAD

**Issue by notklaatu** [MakerBox-NZ/pygame_bluwattl#10]
Your ``evol`` function is not working correctly, and is causing one platform block (specifically, the last platform drawn to the screen) to float out of sync with other platforms. 

Comment out the ``for evol in evol_list`` lines in your foward and backward scroll code for proof.

If confused, talk to me in class. To be honest, I'm not clear on how ``evol`` differs from ``loot``, so you might be making it more complex than necessary.

**Comment by bluwattl** [comment]
Things in `evol_list` increase stats such as jumping and speed.
