### ISSUE TITLE
Image File Location?

### ISSUE THREAD

**Issue by cyanidecupcake** [MakerBox-NZ/pygame_bluwattl#14]
![screen shot 2017-09-18 at 2 13 12 pm](https://user-images.githubusercontent.com/13429860/30527351-bb533cf4-9c7b-11e7-8e9d-301ed694ef61.png)

It looks like you are directing Pygame to open a file named 'guy' with no extension.   I also don't see a file named guy in your images folder.

**Comment by bluwattl** [comment]
That is a variable that is defined in Preinit.​
