### ISSUE TITLE
i cant grab that meat and im hungry 

### ISSUE THREAD

**Issue by bluwattl** [MakerBox-NZ/pygame_bluwattl#7]
👎  is that pixel creature a llama or a donkey im not sure

**Comment by bluwattl** [comment]
Neither am I, self.

**Comment by cyanidecupcake** [comment]
It's obviously a llama, because llamas are the best.

**Comment by bluwattl** [comment]
It's a dinosaur, because I don't know how to make projectiles. (spit)

**Comment by bluwattl** [comment]
The actual issue is something that I have no idea about.

**Comment by cyanidecupcake** [comment]
Can you be more specific about what you want to happen or what is happening that you think shouldn't be?  If you give us more details we can probably help!

**Comment by bluwattl** [comment]
It is fixed!
