### ISSUE TITLE
Extra Floating Platform

### ISSUE THREAD

**Issue by cyanidecupcake** [MakerBox-NZ/pygame_bluwattl#8]
There is an extra platform that appears when player scrolls (turns up about 7 platforms in), but then scrolls away faster than the rest of the platforms.  

@notklaatu and I should definitely look into this.

![floatingplatform](https://user-images.githubusercontent.com/13429860/30039715-0b6b455e-9229-11e7-8014-082a456bd2a2.png)

**Comment by bluwattl** [comment]
![hero](https://user-images.githubusercontent.com/22335811/30094834-d4f02972-9322-11e7-9f57-15652534e4b2.png)
This guy is happy that this confusing error is FIXED!
